# Generated by Django 3.0.6 on 2020-07-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pre_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
